# Generated by Django 2.2.12 on 2022-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='well',
            name='lastname',
        ),
        migrations.AddField(
            model_name='well',
            name='name',
            field=models.CharField(default='------', max_length=255),
        ),
    ]
