# Generated by Django 2.2.12 on 2022-06-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('wells', '0002_auto_20220621_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.User'),
        ),
    ]
